language: ruby
rvm:
- 2.2
- 2.1
- 2.0
- 1.9
before_install:
- echo "deb http://http.debian.net/debian jessie-backports main" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install -qq libgrpc-dev
