language: ruby
rvm:
- 2.2
- 2.1
- 2.0
before_install:
- echo "deb http://http.debian.net/debian jessie-backports main" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -y
- sudo apt-get install libgrpc-dev -y --force-yes
